Basic line length module
Algomorph/CodeGrader pull request #102
Opened 2021-04-09 21:05 UTC by Algomorph

The module draws a print margin in each code file after the specified character line length bound and places labels / buttons on lines that exceed the limit.

2021-04-09 21:26 UTC, msimmon6 requested changes
The module itself looks great! The only two things I noticed were
1) You have "moodule" instead of "module" in 4 places - 2 in the module itself, 1 in options, and 1 in submit server main. Doesn't affect the code but looks silly.
2) In the getMonospaceCharacterWidth function, I don't think you're including all the characters (e.g., \ ' - ` > < = are all the ones I can think of right now). I'd try to look at a list of all the possible characters (which is UTF-8 for the submit server, but CP-1252 by default in Eclipse, so think about that).

2021-04-09 21:55 UTC, Algomorph commented
> The module itself looks great! The only two things I noticed were
> 
> 1. You have "moodule" instead of "module" in 4 places - 2 in the module itself, 1 in options, and 1 in submit server main. Doesn't affect the code but looks silly.

Fixed, thanks :+1: 
> 2. In the getMonospaceCharacterWidth function, I don't think you're including all the characters (e.g., \ ' - ` > < = are all the ones I can think of right now). I'd try to look at a list of all the possible characters (which is UTF-8 for the submit server, but CP-1252 by default in Eclipse, so think about that).

Not much important. The multiple different characters are included on the offchance the font isn't monospace. For monospace-only, it should work just fine with a hundred 'x' characters strung together.

2021-04-09 21:59 UTC, msimmon6 approved these changes
I'm not sure what the getMonospaceCharacterWidth function does anymore, but you sound confident, so I'm sure it's fine! :)

2021-04-11 18:07 UTC, william8siew approved these changes

2021-04-11 21:12 UTC, merged